#!/bin/sh

if [ "$1" = "" ]; then
   echo 'usage: iotedgeinit <domain>'
   exit 0
fi

DEVLIST=/var/tmp/dpride/.iotx/dl
TEMPLATE=/var/tmp/dpride/template.json

iothubman list | devicelist.awk -v domain="$1" > "${DEVLIST}"

cat ${TEMPLATE} | jsonproc.awk -v domain="$1" -v devlist="${DEVLIST}" -v cs=`cat /var/tmp/dpride/.iotx/cs`

